### ISSUE TITLE
xmonad-contrib is pointing at xmonad

### ISSUE THREAD

**Issue by colonelpanic8** [alternateved/nixos-config#1]
https://github.com/alternateved/nixos-config/blob/14ab41496b73e2b6018c5b5b1e02775ea1ae35bb/flake.nix#L10

**Comment by colonelpanic8** [comment]
I would recommend not pointing at my repos, as well. I do my own stuff with these forks, and there are no guarantees about what you will be pointing at, especially with xmonad-contrib.

**Comment by alternateved** [comment]
Ah, my bad. I tried to quickly replicate previous approach and missed the `-contrib` part during the process. Nevertheless, even with that fixed it wouldn't work.

**Comment by colonelpanic8** [comment]
> Ah, my bad. I tried to quickly replicate previous approach and missed the `-contrib` part during the process. Nevertheless, even with that fixed it wouldn't work.

@alternateved what is the error message?

**Comment by alternateved** [comment]
With that setting, I have to explicity declare ghc in system packages in order to be able to recompile xmonad. But it's also not enough, since xmonad cannot find xmonad-contrib modules. So for now I have a list of those kind of errors:
```
    Could not find module ‘XMonad’
    Perhaps you meant DsMonad (needs flag -package-key ghc-8.10.4)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
13 | import XMonad hiding ((|||))
   | ^^^^^^
```

**Comment by colonelpanic8** [comment]
> With that setting, I have to explicity declare ghc in system packages in order to be able to recompile xmonad. But it's also not enough, since xmonad cannot find xmonad-contrib modules. So for now I have a list of those kind of errors:

how are you trying to trigger the recompilation though? are you just calling xmonad --recompile on the command line? Yeah thats not going to work, properly. You need to use a nix aware recompile command.

This is why i hate this whole business of xmonad recompiling itself. XMonad just shouldn't try to pretend that its a binary. It's NOT, it's a library for building a tiling wm.

**Comment by alternateved** [comment]
Yes, I was using xmonad --recompile. And I also realize that it doesn't see main xmonad modules either. Most likely since ghc was installed outside of xmonad context. I am not sure how I could use a nix aware recompile command, but I have a feeling that this is somehow related to this part of your xmonad.hs code:
```
restartEventHook e@ClientMessageEvent { ev_message_type = mt } = do
  a <- getAtom "XMONAD_RESTART"
  if mt == a
    then XMonad.Operations.restart "imalison-xmonad" True >> return (All True)
    else return $ All True
restartEventHook _ = return $ All True
```
But if I understand the process correctly, this restartEventHook is used to restart (proper) xmonad after NixOS has been rebuilt. Anyway, I think the best approach (and most in line with NixOS way) would be to create a small Haskell project as you have mentioned in reddit thread. I will try to set this up.

**Comment by alternateved** [comment]
Well, I tried to setup xmonad as a derivation and use it as a session, but it didn't work. I am afraid I hardly understand anything about the process, though. The setup is the last commit of this repo. When I boot into Nixos, there is a black screen and no window manager is active. Derivation alternateved-xmonad is not in path, although xmonad is.

**Comment by colonelpanic8** [comment]
> Well, I tried to setup xmonad as a derivation and use it as a session, but it didn't work. I am afraid I hardly understand anything about the process, though. The setup is the last commit of this repo. When I boot into Nixos, there is a black screen and no window manager is active. Derivation alternateved-xmonad is not in path, although xmonad is.

I will take a look

**Comment by colonelpanic8** [comment]
It looks like the binary would be called "alternateved_64-linux"
See https://github.com/alternateved/nixos-config/blob/f9abdc28114e029384097d68aa5dda33bb07eb01/home/config/xmonad/alternateved-xmonad.cabal#L6

**Comment by alternateved** [comment]
Thank you for your help. Everything seems to be working, I can also use latest modules from xmonad-contrib. You helped me tremendously. My last question would be - how should I work with recompiling xmonad now? 

As I understand, Nixos is recompiling my alternateved-xmonad package everytime I am rebuilding flake. But how would one go about restarting xmonad within active session, is that even a possibility? For now, after every recompilation, I have to logout and login again.

**Comment by colonelpanic8** [comment]
> As I understand, Nixos is recompiling my alternateved-xmonad package everytime I am rebuilding flake. But how would one go about restarting xmonad within active session, is that even a possibility? For now, after every recompilation, I have to logout and login again.

Right, there are a few ways you can accomplish this. But before I explain, let me say that I do think that this type of xmonad self recompilation is a misfeature, especially in a nixos environment. Why would you want to make this aspect of your build not reproducible.

Anyway, there are a few things you can do:
- I have a sort of halfway solution, that allows me to restart xmonad at the same binary path, but requires me to manually trigger recompliation by doing a system rebuild. I do this because its important that I still be running a binary that is built as part of the system rebuild. The way this works is that I have my own intercept of the restart command: https://github.com/IvanMalison/dotfiles/blob/a14322b4c10778571094ccfec19cbec11a64b44b/dotfiles/config/xmonad/xmonad.hs#L121 that instead of trying any recompilation or special binary paths, just restarts xmonad with a fixed binary name ("imalison-xmonad"). This only works, if the binary imalison-xmonad has changed, so again this still requires system recompilation, but not necessary a logout/login. You can manually trigger restart with the NORMAL xmonad binary with `xmonad --restart`

- If you REALLY want a self-recompliation binding that executes in place, xmonad allows you to specify a custom build script by I believe putting an executable script called "build" in the xmonad configuration directory. Here are some docs that further explain this: https://github.com/xmonad/xmonad/blob/3e762702454b86a7eb35b893e424ad56a801067b/INSTALL.md#L202

In your case, you will need to make the build nix aware. This will likely entail adding a flake.nix file that is local to the xmonad directory that ONLY builds xmonad. I have actually done this in my dotfiles (since I like to be able to test recompilation there), so you can copy the approach from there:

https://github.com/IvanMalison/dotfiles/blob/master/dotfiles/config/xmonad/flake.nix

Your build script will then invoke this build using `nix build` and then copy the binary from ./result/bin/alternateved-xmonad to whereever you are supposed to copy it to for that build script.

**Comment by alternateved** [comment]
Ah, I see. I was using your flake.nix approach from the beginning, so the flake file is in the xmonad directory. 

The first solution seems great - especially since it is in line with Nixos. I really don't need this self-recompilation feature. It's not like I am constantly tweaking so much within xmonad.hs.

Thank you very much. I've learned so much about xmonad within Haskell and I am really glad that it was possible to use latest xmonad within this context.

**Comment by liskin** [comment]
So, um, does this mean we have an official flake.nix in the xmonad repo where recompilation doesn't really work? Shouldn't that at least be documented?

I mean, I also haven't used xmonad --recompile for like 5+ years or something, so I can relate to @IvanMalison's approach towards that, but on the other hand it's a feature that most ordinary users rely upon and that most of our documentation points towards, so we should either fix it or add nix-specific documentation that explains how to work around that.

**Comment by colonelpanic8** [comment]
@liskin It's not so much that it does not work, but that it would require additional configuration for things to work. How is this any different than the situation with e.g. stack? xmonad --recompile would not work with a stack build out of the box (you would need to specify a custom build script). Same thing applies here.

**Comment by liskin** [comment]
@IvanMalison It does in fact work with stack out of the box if people follow the INSTALL.md since https://github.com/xmonad/xmonad/pull/318, and even before that the exact custom build script to use was documented prominently in there. So… "same thing applies here" ;-P

**Comment by colonelpanic8** [comment]
xmonad/xmonad#318 was merged after xmonad/xmonad#316, so I think the onus to have a similar feature for nix would have fallen there.

If you'd like to add something to install.md to describe how to do something similar with nix, I'm certainly fine with that.

Personally, I find self recompilation to be a misfeature, and something we should be steering people away from.

**Comment by liskin** [comment]
> If you'd like to add something to install.md to describe how to do something similar with nix, I'm certainly fine with that.

Yes, I'd love that, I just don't feel qualified to be doing it, and I don't really have the time to become qualified either. :-/

**Comment by alternateved** [comment]
I would really like to help, but I also don't feel qualified enough for that.

**Comment by colonelpanic8** [comment]
> Yes, I'd love that, I just don't feel qualified to be doing it, and I don't really have the time to become qualified either. :-/

I don't think it requires expertise to understand that the command one would run is nix-build...

Otherwise it should be quite similar to the stack build process.

Seems like something like xmonad/xmonad#318 should be implemented for nix

**Comment by colonelpanic8** [comment]
@liskin I added recompilation support for nix here https://github.com/xmonad/xmonad/pull/330. Lets continue discussion there.
